name: Deploy to central

on:
  release:
    types: [ prereleased ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    name: Release build and publish
    runs-on: macOS-latest
    env:
        MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        MAVEN_SIGNING_KEY_ID: ${{ secrets.MAVEN_SIGNING_KEY_ID }}
        MAVEN_SIGNING_PASSWORD: ${{ secrets.MAVEN_SIGNING_PASSWORD }}
        MAVEN_GPG_KEY_CONTENTS: ${{ secrets.MAVEN_GPG_KEY_CONTENTS }}
    steps:
      - uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.MAVEN_GPG_KEY_CONTENTS }}
          passphrase: ${{ secrets.MAVEN_SIGNING_PASSWORD }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Publish Fanbox library to MavenCentral
        run: ./gradlew :fankt:fanbox:publishAndReleaseToMavenCentral --no-configuration-cache

      - name: Publish Fantia library to MavenCentral
        run: ./gradlew :fankt:fantia:publishAndReleaseToMavenCentral --no-configuration-cache
